site_name: POSTED Documentation
site_url: https://philippverpoort.github.io/posted/
repo_name: POSTED
repo_url: https://github.com/PhilippVerpoort/posted/

copyright: Â© POSTED Contributors 2023 | <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>

theme:
  logo: assets/logos/logo-header.svg
  favicon: assets/logos/favicon.ico
  palette:
    primary: custom
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - toc.integrate
    # - announce.dismiss
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

extra:
  version:
    default: latest
    provider: mike
    alias: true

extra_css:
  - assets/css/extra.css
  - assets/css/theme-toggle.css

extra_javascript:
- assets/js/plotly-theme.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
- attr_list
- md_in_html
- tables
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: yes
- pymdownx.snippets:
    base_path: docs
- pymdownx.arithmatex:
    generic: yes
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
- awesome-nav:
    filename: docs/nav.yaml
- mkdocs-jupyter:
    execute: false
    show_input: false
    no_input: true
    include: ["*.ipynb"]
    include_source: true
- markdown-exec
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
