[tool.poetry]
name = "posted"
version = "0.3.0"
description = "POSTED: Potsdam Open-Source Techno-Economic Database"
authors = [
    "Philipp C. Verpoort <philipp.verpoort@pik-potsdam.de>",
    "Paul Effing <paul.effing@pik-potsdam.de>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/PhilippVerpoort/posted/"
packages = [
    {include = "posted", from = "python"},
]
include = ["python/posted/data/**/*"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyyaml = "^6.0"
numpy = "^1.24.2"
pandas = "^2.0.2"
pint = "^0.22.0"
sigfig = "^1.3.2"
pybtex = "^0.24.0"
pybtex-apa-style = "^1.3"
iam-units = "^2023.9.12"

[tool.poetry.group.gui.dependencies]
pyside6 = "^6.5.0"


[tool.poetry.group.dev.dependencies]
matplotlib = "^3.8.2"
plotly = "^5.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = "build_attach_data.py"

[tool.poetry.scripts]
posted = 'posted.cmdline:main'
