name: Docs (latest)

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Build and deploy docs of latest commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sync dependencies
        run: |
          uv sync --group docs

      - name: Register docs kernel
        run: |
          uv run scripts/register_docs_kernel.py

      - name: Execute Jupyter notebooks
        run: |
          BUILD_POSTED_DOCS=1 uv run jupytext --to notebook --execute docs/data/*.py

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Run mike to deploy mkdocs as latest
        run: |
          uv run mike deploy latest --update-aliases

      - name: Push gh-pages branch
        run: |
          git push origin gh-pages
